# version: "3"

# services:
#   frontend:
#     build:
#       context: .
#       dockerfile: Frontend/Dockerfile
#     image: frontend:latest
#     ports:
#       - 8501:8501
#     networks:
#       - project_network
#     depends_on:
#       - backend
#       - sqlserver
#     volumes:
#       - ./Frontend:/app/backend


#   backend:
#     build:
#       context: .
#       dockerfile: Backend/Dockerfile
#     image: backend:latest
#     ports:
#       - 8080:8080
#     networks:
#       - project_network
#     depends_on:
#       - sqlserver
#     environment:
#       - DATABASE_URL=sqlserver  # Pass SQL Server hostname to backend

#   sqlserver:
#     image: mcr.microsoft.com/mssql/server:2022-latest
#     container_name: sqlserver
#     environment:
#       - ACCEPT_EULA=Y
#       - SA_PASSWORD=admin@1234  # Set your SA password
#     ports:
#       - "1433:1433"
#     networks:
#       - project_network
#     volumes:
#       - sql_data:/var/opt/mssql

# networks:
#   project_network:

# volumes:
#   sql_data:

version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    image: frontend:latest
    ports:
      - "8501:8501"
    networks:
      - project_network
    depends_on:
      - backend
      - sqlserver
    volumes:
      - ./Frontend:/app/backend

  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    image: backend:latest
    ports:
      - "8080:8080"
    networks:
      - project_network
    depends_on:
      - sqlserver
    environment:
      - DATABASE_URL=mssql://sa:admin@1234@sqlserver:1433/RecoMaster  # SQL Server connection string

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=admin@1234  # Set your SA password
    ports:
      - "1433:1433"
    networks:
      - project_network
    volumes:
      - sql_data:/var/opt/mssql
      - ./RecoMaster.bak:/var/opt/mssql/backup/RecoMaster.bak  # Mount the .bak file
    command:
      - /bin/bash
      - -c
      - |
        /opt/mssql/bin/sqlservr & \
        sleep 30s && \
        /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P admin@1234 -Q "RESTORE DATABASE [RecoMaster] FROM DISK = N'/var/opt/mssql/backup/RecoMaster.bak' WITH MOVE 'RecoMaster' TO '/var/opt/mssql/data/RecoMaster.mdf', MOVE 'RecoMaster_log' TO '/var/opt/mssql/data/RecoMaster_log.ldf';"

networks:
  project_network:

volumes:
  sql_data:
